import React from 'react'

const Home = () => {
  return (
    <div className='bg-(--base)'>
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam assumenda necessitatibus totam voluptate. Asperiores aut, ullam, magni impedit velit ex dignissimos omnis earum enim reprehenderit nisi incidunt blanditiis sapiente quaerat doloremque magnam veniam harum laborum? Temporibus iste maiores earum magni quam natus incidunt, quis commodi repudiandae iusto, hic odio distinctio amet vel excepturi. Porro laudantium eos odio temporibus soluta, officia ut facere modi a doloremque accusantium quisquam sapiente aliquid aut. Ipsam architecto velit quaerat dicta expedita eveniet ipsa beatae unde quibusdam, eius rerum eligendi inventore possimus reprehenderit autem et at quod. Adipisci provident deleniti laudantium pariatur, dolores rem excepturi atque eos quisquam expedita blanditiis molestias, autem aliquid dolorum, doloribus illum velit magnam dolore impedit labore! Accusamus doloribus laboriosam sunt dolor placeat vel beatae quo! Dicta, ipsa temporibus! Deserunt, reiciendis? Facere nam quo aut similique, odio inventore beatae illum excepturi omnis tempore assumenda nisi, adipisci, obcaecati accusantium. Ut fuga culpa iure eos perferendis, debitis error dignissimos quia dolorem, ipsum mollitia sapiente neque, tempore nisi assumenda dolorum. Eius, eligendi nostrum. Nulla, inventore rerum laborum optio veniam dolor qui dignissimos, expedita, est quo assumenda commodi odio eveniet laboriosam praesentium officia? Quibusdam, molestiae veniam sunt dolores tenetur est, quod asperiores laborum voluptatum quis culpa perferendis eaque saepe velit, aspernatur voluptate deleniti! Ducimus hic illo in mollitia iusto quas dignissimos aperiam vitae obcaecati quibusdam, itaque impedit culpa quidem, nam molestiae ipsa incidunt nisi ex sequi voluptatum inventore amet minus quisquam neque? Sit praesentium sapiente saepe officia excepturi, cumque non nulla quae facere deserunt delectus similique iste vitae? Tenetur autem quas numquam qui quidem illum laudantium modi nostrum fuga quasi rerum blanditiis commodi voluptatum reiciendis quo, iure ut obcaecati odit assumenda dolorem dolor voluptas! Mollitia vero cupiditate laborum pariatur maxime deleniti quas iure laboriosam. Maiores quidem cum rem autem, illum nemo labore reprehenderit? Minus, voluptate labore!
    </div>
  )
}

export default Home